In [2]:
import pandas as pd

-------------------

# Fazendo o processo de ETL no python

In [3]:
df = pd.read_excel("DADOS\\brasileirao.xlsx")

In [24]:
lista = df['Club'].unique()

In [25]:
clubes_ordenados = sorted(lista)

In [26]:
clubes_ordenados

['América Mineiro',
 'América-RN',
 'Athletico Paranaense',
 'Atlético Goianiense',
 'Atlético Mineiro',
 'Atlético Paranaense',
 'Avaí',
 'Bahia',
 'Barueri',
 'Botafogo',
 'Bragantino',
 'Brasiliense',
 'CSA',
 'Ceará',
 'Chapecoense',
 'Corinthians',
 'Coritiba',
 'Criciúma',
 'Cruzeiro',
 'Cuiabá',
 'Figueirense',
 'Flamengo',
 'Fluminense',
 'Fortaleza',
 'Goiás',
 'Grêmio',
 'Grêmio Prudente',
 'Guarani',
 'Internacional',
 'Ipatinga',
 'Joinville',
 'Juventude',
 'Náutico',
 'Palmeiras',
 'Paraná',
 'Paysandu',
 'Ponte Preta',
 'Portuguesa',
 'Santa Cruz',
 'Santo André',
 'Santos',
 'Sport',
 'São Caetano',
 'São Paulo',
 'Vasco',
 'Vasco da Gama',
 'Vitória']

In [7]:
mappings = {'América-MG': 'América Mineiro', '\xa0Santos': 'Santos'}
df['Club'] = df['Club'].replace(mappings)

In [8]:
lista = df['Club'].unique()

In [9]:
df.to_excel("DADOS\\Brasileirao.xlsx",index=False)

---------------

In [10]:
df1 = pd.read_excel("DADOS\\brasileirao_serie_a.xlsx")

In [11]:
df1.head()

,ano_campeonato,data,rodada,estadio,arbitro,publico,publico_max,time_mandante,time_visitante,tecnico_mandante,...,chutes_bola_parada_mandante,chutes_bola_parada_visitante,defesas_mandante,defesas_visitante,impedimentos_mandante,impedimentos_visitante,chutes_mandante,chutes_visitante,chutes_fora_mandante,chutes_fora_visitante
0,2003,2003-05-11,8,Arena do Grêmio,NaN,NaN,NaN,Grêmio,Coritiba FC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2003,2003-06-15,13,Arena do Grêmio,NaN,NaN,NaN,Grêmio,Internacional,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2003,2003-07-06,16,Arena do Grêmio,NaN,NaN,NaN,Grêmio,Flamengo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2003,2003-08-02,23,Arena do Grêmio,NaN,NaN,NaN,Grêmio,Santos FC,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2003,2003-08-23,28,Arena do Grêmio,NaN,NaN,NaN,Grêmio,São Caetano,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
lista1 = df1['time_mandante'].unique()

In [13]:
lista1 = sorted(lista1)

In [14]:
lista1

['América Mineiro',
 'América-RN',
 'Athletico Paranaense',
 'Atlético Goianiense',
 'Atlético Mineiro',
 'Atlético Paranaense',
 'Avaí',
 'Bahia',
 'Barueri',
 'Botafogo',
 'Bragantino',
 'Brasiliense',
 'CSA',
 'Ceará',
 'Chapecoense',
 'Corinthians',
 'Coritiba',
 'Criciúma',
 'Cruzeiro',
 'Cuiabá',
 'Figueirense',
 'Flamengo',
 'Fluminense',
 'Fortaleza',
 'Goiás',
 'Grêmio',
 'Guarani',
 'Internacional',
 'Ipatinga',
 'Joinville',
 'Juventude',
 'Náutico',
 'Palmeiras',
 'Paraná',
 'Paysandu',
 'Ponte Preta',
 'Portuguesa',
 'Santa Cruz',
 'Santo André',
 'Santos',
 'Sport',
 'São Caetano',
 'São Paulo',
 'Vasco da Gama',
 'Vitória']

In [15]:
mappings = {'América-MG' : 'América Mineiro',
 'Athletico-PR': 'Athletico Paranaense',
 'Atlético-GO': 'Atlético Goianiense',
 'Atlético-MG': 'Atlético Mineiro',
 'Atlético-PR': 'Atlético Paranaense',
 'AvaÃ\xad FC': 'Avaí',
 'Brasiliense-DF' : 'Brasiliense',
 'Ceará SC' : 'Ceará',
 'Coritiba FC' : 'Coritiba',
 'Criciúma EC' : 'Criciúma',
 'Cuiabá-MT' : 'Cuiabá',
 'EC Bahia' :'Bahia',
 'EC Vitória': 'Vitória',
 'Figueirense FC': 'Figueirense',
 'Goiás EC' :'Goiás',
 'Ipatinga FC' : 'Ipatinga',
 'Joinville-SC' : 'Joinville',
 'Paysandu SC' : 'Paysandu',
 'RB Bragantino' : 'Bragantino',
 'Santos FC' : 'Santos',
 'Sport Recife' : 'Sport',
 }
df1['time_mandante'] = df1['time_mandante'].replace(mappings)
df1['time_visitante'] = df1['time_visitante'].replace(mappings)

In [16]:
df1.to_excel("DADOS\\brasileirao_serie_a.xlsx",index=False)

----------

In [17]:
df2 = pd.read_csv("DADOS\\campeonato-brasileiro-cartoes.csv")
df2.head()

,partida_id,rodata,clube,cartao,atleta,num_camisa,posicao,minuto
0,4607,1,Figueirense,Amarelo,Paulo Roberto da Silva,28.0,NaN,66
1,4608,1,Internacional,Amarelo,Andrés D'Alessandro,10.0,Meio-campo,72
2,4608,1,Vitoria,Amarelo,Marcelo Machado dos Santos,29.0,NaN,86
3,4608,1,Vitoria,Amarelo,Mansur,NaN,Zagueiro,10
4,4607,1,Figueirense,Amarelo,Thiago Heleno,4.0,Zagueiro,44

In [18]:
lista1 = df2['clube'].unique()

In [19]:
lista1 = sorted(lista1)
lista1

['America-MG',
 'Athletico-PR',
 'Atletico-GO',
 'Atletico-MG',
 'Avai',
 'Bahia',
 'Botafogo-RJ',
 'Bragantino',
 'CSA',
 'Ceara',
 'Chapecoense',
 'Corinthians',
 'Coritiba',
 'Criciuma',
 'Cruzeiro',
 'Cuiaba',
 'Figueirense',
 'Flamengo',
 'Fluminense',
 'Fortaleza',
 'Goias',
 'Gremio',
 'Internacional',
 'Joinville',
 'Juventude',
 'Palmeiras',
 'Parana',
 'Ponte Preta',
 'Santa Cruz',
 'Santos',
 'Sao Paulo',
 'Sport',
 'Vasco',
 'Vitoria']

In [20]:
mappings = {'America-MG' : 'América Mineiro',
 'Athletico-PR' : 'Athletico Paranaense',
 'Atletico-GO' : 'Atlético Goianiense',
 'Atletico-MG' :  'Atlético Mineiro',
 'Avai' : 'Avaí',
 'Botafogo-RJ' : 'Botafogo',
 'Ceara' :'Ceará',
 'Criciuma':"Criciúma",
 'Cuiaba':'Cuiabá',
 'Goias':'Goiás',
 'Gremio':'Grêmio',
 'Parana':'Paraná',
 'Sao Paulo' : 'São Paulo',
 'Vitoria':'Vitória'}
df2['clube'] = df2['clube'].replace(mappings)

In [21]:
df2.to_excel("DADOS\\campeonato-brasileiro-cartoes.xlsx",index=False)

-------------------

In [22]:
df3 = pd.read_csv("DADOS\\campeonato-brasileiro-estatisticas-full.csv")
df3.head()

,partida_id,rodata,clube,chutes,chutes_no_alvo,posse_de_bola,passes,precisao_passes,faltas,cartao_amarelo,cartao_vermelho,impedimentos,escanteios
0,1,1,Guarani,0,0,NaN,0,NaN,0,0,0,0,0
1,1,1,Vasco,0,0,NaN,0,NaN,0,0,0,0,0
2,2,1,Athletico-PR,0,0,NaN,0,NaN,0,0,0,0,0
3,2,1,Gremio,0,0,NaN,0,NaN,0,0,0,0,0
4,3,1,Flamengo,0,0,NaN,0,NaN,0,0,0,0,0

In [23]:
lista1 = df3['clube'].unique()
lista1 = sorted(lista1)
lista1

['America-MG',
 'America-RN',
 'Athletico-PR',
 'Atletico-GO',
 'Atletico-MG',
 'Avai',
 'Bahia',
 'Barueri',
 'Botafogo-RJ',
 'Bragantino',
 'Brasiliense',
 'CSA',
 'Ceara',
 'Chapecoense',
 'Corinthians',
 'Coritiba',
 'Criciuma',
 'Cruzeiro',
 'Cuiaba',
 'Figueirense',
 'Flamengo',
 'Fluminense',
 'Fortaleza',
 'Goias',
 'Gremio',
 'Gremio Prudente',
 'Guarani',
 'Internacional',
 'Ipatinga',
 'Joinville',
 'Juventude',
 'Nautico',
 'Palmeiras',
 'Parana',
 'Paysandu',
 'Ponte Preta',
 'Portuguesa',
 'Santa Cruz',
 'Santo Andre',
 'Santos',
 'Sao Caetano',
 'Sao Paulo',
 'Sport',
 'Vasco',
 'Vitoria']

In [27]:
mappings = {'America-MG' : 'América Mineiro',
 'Athletico-PR':  'Athletico Paranaense',
 'Atletico-GO' : 'Atlético Goianiense',
 'Atletico-MG' :  'Atlético Mineiro',
 'Avai' :'Avaí',
 'Botafogo-RJ' :'Botafoto',
 'Ceara' : 'Ceará',
 'Criciuma' : 'Criciúma',
 'Cuiaba' : 'Cuiabá',
 'Goias' : 'Goiás',
 'Gremio':'Grêmio',
 'Gremio Prudente':'Grêmio Prudente',
 'Nautico' : 'Náutico',
 'Parana' : 'Paraná',
 'Santo Andre' : "Santo André",
 'Sao Caetano' : 'São Caetano',
 'Sao Paulo' : 'São Paulo',
 'Vitoria' : 'Vitória'}
df3['clube'] = df3['clube'].replace(mappings)

In [28]:
df3.to_excel("DADOS\\campeonato-brasileiro-estatisticas-full.xlsx",index=False)

----------------

In [30]:
df4 = pd.read_csv("DADOS\\campeonato-brasileiro-full.csv")
df4.head()

,ID,rodata,data,hora,mandante,visitante,formacao_mandante,formacao_visitante,tecnico_mandante,tecnico_visitante,vencedor,arena,mandante_Placar,visitante_Placar,mandante_Estado,visitante_Estado
0,1,1,29/3/2003,16:00,Guarani,Vasco,NaN,NaN,NaN,NaN,Guarani,Brinco de Ouro,4,2,SP,RJ
1,2,1,29/3/2003,16:00,Athletico-PR,Gremio,NaN,NaN,NaN,NaN,Athletico-PR,Arena da Baixada,2,0,PR,RS
2,3,1,30/3/2003,16:00,Flamengo,Coritiba,NaN,NaN,NaN,NaN,-,Maracanã,1,1,RJ,PR
3,4,1,30/3/2003,16:00,Goias,Paysandu,NaN,NaN,NaN,NaN,-,Serra Dourada,2,2,GO,PA
4,5,1,30/3/2003,16:00,Internacional,Ponte Preta,NaN,NaN,NaN,NaN,-,Beira Rio,1,1,RS,SP

In [33]:
lista1 = df4['mandante'].unique()
lista1 = sorted(lista1)
lista1

['America-MG',
 'America-RN',
 'Athletico-PR',
 'Atletico-GO',
 'Atletico-MG',
 'Avai',
 'Bahia',
 'Barueri',
 'Botafogo-RJ',
 'Bragantino',
 'Brasiliense',
 'CSA',
 'Ceara',
 'Chapecoense',
 'Corinthians',
 'Coritiba',
 'Criciuma',
 'Cruzeiro',
 'Cuiaba',
 'Figueirense',
 'Flamengo',
 'Fluminense',
 'Fortaleza',
 'Goias',
 'Gremio',
 'Gremio Prudente',
 'Guarani',
 'Internacional',
 'Ipatinga',
 'Joinville',
 'Juventude',
 'Nautico',
 'Palmeiras',
 'Parana',
 'Paysandu',
 'Ponte Preta',
 'Portuguesa',
 'Santa Cruz',
 'Santo Andre',
 'Santos',
 'Sao Caetano',
 'Sao Paulo',
 'Sport',
 'Vasco',
 'Vitoria']

In [35]:
mappings = {'America-MG':'América Mineiro',
 'Athletico-PR':'Athletico Paranaense',
 'Atletico-GO': 'Atlético Goianiense',
 'Atletico-MG': 'Atlético Mineiro',
 'Avai':'Avaí',
 'Botafogo-RJ':'Botafogo',
 'Ceara':'Ceará',
 'Criciuma':'Criciúma',
 'Cuiaba':'Cuiabá',
 'Goias':'Goiás',
 'Gremio':'Grêmio',
 'Gremio Prudente':'Grêmio Prudente',
 'Nautico':'Náutico',
 'Parana':'Paraná',
 'Santo Andre':'Santo André',
 'Sao Caetano': 'São Caetano',
 'Sao Paulo':'São Paulo',
 'Vitoria':'Vitória'}
df4['mandante'] = df4['mandante'].replace(mappings)
df4['visitante'] = df4['visitante'].replace(mappings)
df4['vencedor'] = df4['vencedor'].replace(mappings)

In [37]:
df4.to_excel("DADOS\\campeonato-brasileiro-full.xlsx",index=False)