In [1]:
import pandas as pd

In [2]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from nerodia.browser import Browser
import time
from selenium.webdriver.chrome.options import Options
import warnings
warnings.filterwarnings("ignore")

In [3]:
options = Options()
options.add_argument('--headless')
options.add_argument('--no-sandbox') # Remove if running outside deepnotel

In [35]:
def Pokemon():
    browser = Browser('chrome', options=options) # Create Browser
    browser.goto('https://www.serebii.net/pokemon/gen1pokemon.shtml') #LINK de acesso ao dataset
    # browser.goto('https://pokemondb.net/pokedex/all')
    time.sleep(4) # Coloda o scrip em pausa enquanto a página carrega

    df = pd.read_html(browser.html)[0]
    df = df.drop([1,3], axis=1)
    df = df.dropna()
    df = df.reset_index(drop=True)
    novo_cabecalho = df.iloc[1].tolist()
    df = df.iloc[2:]
    df.columns = novo_cabecalho
    df['No.'] = df['No.'].str[-3:]
    df.loc[df['Name'] == 'Nidoran♀', 'Name'] = 'Nidoran-femea'
    df.loc[df['Name'] == 'Nidoran♂', 'Name'] = 'Nidoran'
    df.loc[df['Name'] == "Farfetch'd", 'Name'] = 'farfetchd'
    df.loc[df['Name'] == "Mr. Mime", 'Name'] = 'mrmime'
    return df

In [36]:
df = Pokemon()

In [37]:
df

     No.        Name               Abilities   HP  Att  Def S.Att S.Def  Spd
2    001   Bulbasaur    Overgrow Chlorophyll   45   49   49    65    65   45
3    002     Ivysaur    Overgrow Chlorophyll   60   62   63    80    80   60
4    003    Venusaur    Overgrow Chlorophyll   80   82   83   100   100   80
5    004  Charmander       Blaze Solar Power   39   52   43    60    50   65
6    005  Charmeleon       Blaze Solar Power   58   64   58    80    65   80
..   ...         ...                     ...  ...  ...  ...   ...   ...  ...
148  147     Dratini  Shed Skin Marvel Scale   41   64   45    50    50   50
149  148   Dragonair  Shed Skin Marvel Scale   61   84   65    70    70   70
150  149   Dragonite  Inner Focus Multiscale   91  134   95   100   100   80
151  150      Mewtwo        Pressure Unnerve  106  110   90   154    90  130
152  151         Mew             Synchronize  100  100  100   100   100  100

[151 rows x 9 columns]

In [30]:
def types():
    browser = Browser('chrome', options=options) # Create Browser
    browser.goto('https://charizardpoke.blogspot.com/2014/08/pokedex-kanto1-geracao.html') #LINK de acesso ao dataset
    # browser.goto('https://pokemondb.net/pokedex/all')
    time.sleep(4) # Coloda o scrip em pausa enquanto a página carrega

    df_types = pd.read_html(browser.html)[0]
    df_types['Kdex'] = df_types['Kdex'].str[-3:]
    df_types = df_types.drop(['Ndex','MS','Pokémon'], axis=1)
    df_types = df_types.rename(columns={'Kdex': 'No.'})
    return df_types

In [33]:
df_types = types()
df= pd.merge(df, df_types, on='No.')

In [34]:
df

,No.,Name,Abilities,HP,Att,Def,S.Att,S.Def,Spd,Type_x,Type.1_x,Type_y,Type.1_y
0,001,Bulbasaur,Overgrow Chlorophyll,45,49,49,65,65,45,Grass,Poison,Grass,Poison
1,002,Ivysaur,Overgrow Chlorophyll,60,62,63,80,80,60,Grass,Poison,Grass,Poison
2,003,Venusaur,Overgrow Chlorophyll,80,82,83,100,100,80,Grass,Poison,Grass,Poison
3,004,Charmander,Blaze Solar Power,39,52,43,60,50,65,Fire,Fire,Fire,Fire
4,005,Charmeleon,Blaze Solar Power,58,64,58,80,65,80,Fire,Fire,Fire,Fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,Dratini,Shed Skin Marvel Scale,41,64,45,50,50,50,Dragon,Dragon,Dragon,Dragon
147,148,Dragonair,Shed Skin Marvel Scale,61,84,65,70,70,70,Dragon,Dragon,Dragon,Dragon
148,149,Dragonite,Inner Focus Multiscale,91,134,95,100,100,80,Dragon,Flying,Dragon,Flying
149,150,Mewtwo,Pressure Unnerve,106,110,90,154,90,130,Psychic,Psychic,Psychic,Psychic
150,151,Mew,Synchronize,100,100,100,100,100,100,Psychic,Psychic,Psychic,Psychic

In [84]:
def Description(df):
    List_pokemons = df['Name'].unique()
    List_pokemons = [valor.lower() for valor in List_pokemons]
    Descricao_pokemons = pd.DataFrame()
    for i in List_pokemons:
        try:
            browser = Browser('chrome', options=options) 
            url = 'https://www.heypikachu.com/'+i+'#pokedex'
            browser.goto(url)
            print(i)
            df1 = pd.read_html(browser.html)[5]
            df1[0] = df1[0].str.replace(':', '')
            df1 = df1.set_index(0)
            df1 = df1.transpose()
            df1 = df1.dropna(axis=1)
            df1["Name"] = i
            Descricao_pokemons = Descricao_pokemons.append(df1)
            browser.close()
        except:
            browser = Browser('chrome', options=options) 
            url = 'https://www.heypikachu.com/'+i+'#pokedex'
            browser.goto(url)
            print(i)
            df1 = pd.read_html(browser.html)[7]
            df1[0] = df1[0].str.replace(':', '')
            df1 = df1.set_index(0)
            df1 = df1.transpose()
            df1 = df1.dropna(axis=1)
            df1["Name"] = i
            Descricao_pokemons = Descricao_pokemons.append(df1)
            browser.close()
    return Descricao_pokemons

In [85]:
Descricao_pokemons = Description(df)

bulbasaur
ivysaur

In [13]:
df['Name'] = df['Name'].str.lower()
df_merged = pd.merge(df, Descricao_pokemons, on='Name')

In [12]:
df

     No.        Name               Abilities   HP  Att  Def S.Att S.Def  Spd
2    001   bulbasaur    Overgrow Chlorophyll   45   49   49    65    65   45
3    002     ivysaur    Overgrow Chlorophyll   60   62   63    80    80   60
4    003    venusaur    Overgrow Chlorophyll   80   82   83   100   100   80
5    004  charmander       Blaze Solar Power   39   52   43    60    50   65
6    005  charmeleon       Blaze Solar Power   58   64   58    80    65   80
..   ...         ...                     ...  ...  ...  ...   ...   ...  ...
148  147     dratini  Shed Skin Marvel Scale   41   64   45    50    50   50
149  148   dragonair  Shed Skin Marvel Scale   61   84   65    70    70   70
150  149   dragonite  Inner Focus Multiscale   91  134   95   100   100   80
151  150      mewtwo        Pressure Unnerve  106  110   90   154    90  130
152  151         mew             Synchronize  100  100  100   100   100  100

[151 rows x 9 columns]

In [14]:
df_merged

,No.,Name,Abilities,HP,Att,Def,S.Att,S.Def,Spd,Unnamed: 0,Nome em japonês,Descrição,Gênero provável,Região,Taxa de captura,Altura,Peso,Pegada
0,001,bulbasaur,Overgrow Chlorophyll,45,49,49,65,65,45,1,フシギダネ Fushigidane,Bulbasaur pode ser visto cochilando sob luz so...,"87.5% male, 12.5% female",Kanto (1ª Geração),45 (11.9%),70 cm,6.9 kg,NaN
1,002,ivysaur,Overgrow Chlorophyll,60,62,63,80,80,60,1,フシギソウ Fushigisou,Há um broto nas costas desse Pokémon. Para sup...,"87.5% male, 12.5% female",Kanto (1ª Geração),"45 (5,9%)",1.0 metro,13 kg,NaN
2,003,venusaur,Overgrow Chlorophyll,80,82,83,100,100,80,1,フシギバナ Fushigibana,Há uma flor grande nas costas de Venusaur. Diz...,"87.5% macho, 12.5% fêmea",Kanto (1ª Geração),"45 (5,9%)","2,0 m","100,0 kg",NaN
3,004,charmander,Blaze Solar Power,39,52,43,60,50,65,1,ヒトカゲ Hitokage,A chama que queima na ponta da cauda é uma ind...,"87.5% macho, 12.5% fêmea",Kanto (1ª Geração),"45 (5,9%)",60 cm,"8,5 kg",NaN
4,005,charmeleon,Blaze Solar Power,58,64,58,80,65,80,1,リザード Lizardo,Charmeleon impiedosamente destrói seus inimigo...,"87.5% male, 12.5% female",Kanto (1ª Geração),"45 (5,9%)","1,1 m",19 kg,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,147,dratini,Shed Skin Marvel Scale,41,64,45,50,50,50,1,ミニリュウ Miniryu,Dratini muda constantemente e descama sua pele...,"50,0% macho, 50,0% fêmea",Kanto (1ª Geração),"45 (5,9%)","1,8 m","3,3 kg",não possui
147,148,dragonair,Shed Skin Marvel Scale,61,84,65,70,70,70,1,ハクリュー Hakuryu,Dragonair armazena uma enorme quantidade de en...,"50,0% macho, 50,0% fêmea",Kanto (1ª Geração),"45 (5,9%)",4 m,"16,5 kg",não possui
148,149,dragonite,Inner Focus Multiscale,91,134,95,100,100,80,1,カイリュー Kairyu,Dragonite é capaz de circular o globo em apena...,"50,0% macho, 50,0% fêmea",Kanto (1ª Geração),"45 (5,9%)","2,2 m",210 kg,NaN
149,150,mewtwo,Pressure Unnerve,106,110,90,154,90,130,1,ミュウツー Mewtwo,Mewtwo é um Pokémon que foi criado por manipul...,NaN,Kanto (1ª Geração),"3 (0,4%)","2,0 m",122 kg,NaN
150,151,mew,Synchronize,100,100,100,100,100,100,1,ミュウ Mew,Diz-se que Mew possui a composição genética de...,NaN,Kanto (1ª Geração),"45 (5,9%)",40 cm,4 kg,NaN

In [15]:
df_merged.to_excel('C:\\Users\\kaka_\\Desktop\\Pokemon\\dataset.xlsx')